<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.8.0.1 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php,v 1.23.2.2 2006/02/06 11:01:48 nijel Exp $
 * Date: Wed, 25 Apr 2007 16:55:17 +0200
 */

/* Servers configuration */
$i = 0;

/* Server localhost (cookie) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['connect_type'] = 'socket';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';

/* End of servers configuration */

$cfg['blowfish_secret'] = '6WElcztE6unpAHPofKVhzLwi';
?>
